-- CRIANDO O BANCO DE DADOS
CREATE DATABASE BDLOJAINFO;
-- USANDO O BANCO DE DADOS
USE BDLOJAINFO;

-- CRIANDO AS TABELAS DO BANCO DE DADOS
CREATE TABLE tbUsuario(
CodUsuario INT PRIMARY KEY AUTO_INCREMENT,
NomeUsuario VARCHAR(40) NOT NULL,
SenhaUsuario VARCHAR(40) NOT NULL
);
CREATE TABLE tbFuncionario(
CodFun INT PRIMARY KEY AUTO_INCREMENT,
NomeFunc VARCHAR(50) NOT NULL,
TelFunc VARCHAR(50) NOT NULL
);
CREATE TABLE tbCliente(
CodCli INT PRIMARY KEY AUTO_INCREMENT,
NomeCli VARCHAR(100) NOT NULL,
TelCli VARCHAR(50),
EmailCli VARCHAR(100)
);
CREATE TABLE tbProduto(
CodProd INT PRIMARY KEY AUTO_INCREMENT,
NomeProd VARCHAR(50),
DescProd VARCHAR(200),
ValorUnitario VARCHAR(20)
);
CREATE TABLE tbPagamento(
CodPagto INT PRIMARY KEY AUTO_INCREMENT,
DescPagto VARCHAR(50),
Quantidade INT,
ValorTotal VARCHAR(20)
);

-- INSERINDO DADOS NA TABELA
INSERT INTO tbUsuario(CodUsuario, NomeUsuario, SenhaUsuario) VALUES (1,'edigar','edigar');
-- CONSULTANDO AS TABELAS DO BANCO DE DADOS
SELECT * FROM tbUsuario;
SELECT * FROM tbFuncionario;
SELECT * FROM tbCliente;
SELECT * FROM tbProduto;
SELECT * FROM tbPagamento


